--- !ditz.rubyforge.org,2008-03-06/project 
name: bleeter
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: bleeter
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.0
  status: :released
  release_time: 2010-03-23 12:44:55.680013 Z
  log_events: 
  - - 2010-03-23 06:19:43.271853 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
  - - 2010-03-23 12:44:55.680035 Z
    - James Rowe <jnrowe@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :released
  release_time: 2010-03-28 14:55:33.630487 Z
  log_events: 
  - - 2010-03-23 11:15:48.111855 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
  - - 2010-03-28 14:55:33.630511 Z
    - James Rowe <jnrowe@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.3.0
  status: :released
  release_time: 2010-04-07 07:00:40.123923 Z
  log_events: 
  - - 2010-03-28 15:05:03.026468 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
  - - 2010-04-07 07:00:40.123946 Z
    - James Rowe <jnrowe@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.4.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-04-07 07:00:46.171857 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.5.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-04-21 20:43:34.367799 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
